/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import centrorehabilitacionfisica.Archivo;
import centrorehabilitacionfisica.Medico;
import centrorehabilitacionfisica.Turno;
import java.io.IOException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Cita extends javax.swing.JFrame {

    /**
     * Creates new form Cita
     */
    Turno turno = new Turno();
    Medico medico = new Medico();
    // Especialista especialista = new Especialista();
    private String nombre;
    private String ocupacion;

    public Cita() {

        initComponents();
        rdbEspecialista1.setVisible(false);
        rdbEspecialista2.setVisible(false);
        rdbEspecialista3.setVisible(false);
        rdbEspecialista4.setVisible(false);
        construirTabla();

    }

    private DefaultTableModel modelo2;

    private void construirTabla() {
        try {
            modelo2 = (new DefaultTableModel(obtenerMatriz(), obtenerHeader()));
            jTable1.setModel(modelo2);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.toString() + "error2");
        }
    }

    private String[] obtenerHeader() {
        String titulos[] = {"#REG", "MEDICO", "ESPECIALIDAD", "PACIENTE", "CEDULA", "DIRECCION", "FECHA","ESTADO"};

        return titulos;
    }

    private String[][] obtenerMatriz() {

        Archivo arch = new Archivo();
        String matrizInfo[][] = arch.leerArchivo();

        return matrizInfo;
    }

    public void datos() {
        if (rdbEspecialista1.isSelected() == true) {
            setNombre("Licenciada Adriana Añamisi");
            setOcupacion("FISIOTERAPIA");
        }

        if (rdbEspecialista2.isSelected() == true) {
            setNombre("Licenciada Joselyn Segovia");
            setOcupacion("NUTRICION");
        }

        if (rdbEspecialista3.isSelected() == true) {
            setNombre("Dr.Josefa Martínez");
            setOcupacion("MEDICINA GENERAL");
        }

        if (rdbEspecialista4.isSelected() == true) {
            setNombre("Licenciada Sofía suntaxi");
            setOcupacion("TERAPIA OCUPACIONAL");
        }

        medico.setNombre(nombre);
        medico.setOcupacion(ocupacion);
        medico.setFecha(calendar.getDate());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        btnGrupo2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAgendar = new javax.swing.JButton();
        rdbEspecialista1 = new javax.swing.JRadioButton();
        rdbEspecialista2 = new javax.swing.JRadioButton();
        rdbEspecialista3 = new javax.swing.JRadioButton();
        rdbEspecialista4 = new javax.swing.JRadioButton();
        jlbDisponible = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JDateChooser();
        jblFecha = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jlbDoctor = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel2.setText("AGENDAR CITA");

        btnAgendar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnAgendar.setText("AGENDAR");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });

        btnGrupo.add(rdbEspecialista1);
        rdbEspecialista1.setText("FISIOTERAPIA");
        rdbEspecialista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEspecialista1ActionPerformed(evt);
            }
        });

        btnGrupo.add(rdbEspecialista2);
        rdbEspecialista2.setText("NUTRICION");
        rdbEspecialista2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEspecialista2ActionPerformed(evt);
            }
        });

        btnGrupo.add(rdbEspecialista3);
        rdbEspecialista3.setText("MEDICINA GENERAL");
        rdbEspecialista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEspecialista3ActionPerformed(evt);
            }
        });

        btnGrupo.add(rdbEspecialista4);
        rdbEspecialista4.setText("TERAPIA OCUPACIONAL");
        rdbEspecialista4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEspecialista4ActionPerformed(evt);
            }
        });

        jlbDisponible.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jlbDisponible.setText("ESPECIALIdades");

        calendar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        calendar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calendarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                calendarKeyTyped(evt);
            }
        });

        jblFecha.setFont(new java.awt.Font("Stencil", 1, 12)); // NOI18N
        jblFecha.setText("Confirmar Fecha");
        jblFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblFechaActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jlbDoctor.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jlbDoctor.setText("ESPECIALIdades");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jblFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbEspecialista1)
                    .addComponent(rdbEspecialista2))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdbEspecialista4)
                    .addComponent(rdbEspecialista3)
                    .addComponent(jlbDisponible))
                .addGap(135, 135, 135)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(59, 59, 59))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbDoctor)
                            .addComponent(btnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 986, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlbDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbDoctor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdbEspecialista3)
                                    .addComponent(rdbEspecialista1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(rdbEspecialista4)
                                    .addComponent(rdbEspecialista2))
                                .addGap(45, 45, 45)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jlbDoctor.getAccessibleContext().setAccessibleName("");

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        datos();

        try {
            Paciente paciente = new Paciente(medico);
            paciente.setVisible(true);
            Cita.this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(Cita.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        Ingreso ingreso = new Ingreso();
        ingreso.setVisible(true);

    }//GEN-LAST:event_mnSalirActionPerformed

    private void calendarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarKeyPressed

    }//GEN-LAST:event_calendarKeyPressed

    private void calendarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarKeyTyped

    }//GEN-LAST:event_calendarKeyTyped

    private void jblFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblFechaActionPerformed
        if (turno.tomarCita(calendar.getDate().getDate()) == true) {
            rdbEspecialista1.setVisible(true);
            rdbEspecialista2.setVisible(true);
            rdbEspecialista3.setVisible(false);
            rdbEspecialista4.setVisible(false);

        } else {
            rdbEspecialista1.setVisible(false);
            rdbEspecialista2.setVisible(false);
            rdbEspecialista3.setVisible(true);
            rdbEspecialista4.setVisible(true);
        }

        Archivo arch = new Archivo();
        String[][] datos = arch.leerArchivo();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
        String fechaCalendar = formatter.format(calendar.getDate());

        System.out.println("FECHAS 1: " + fechaCalendar);

        for (int columna = 1; columna < datos.length; columna++) {
            if (fechaCalendar.equals(datos[columna][6])) {
                JOptionPane.showMessageDialog(null, "Existe reservacion para esa fecha, escoja otra");
                break;
            }

        }
    }//GEN-LAST:event_jblFechaActionPerformed

    private void rdbEspecialista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEspecialista3ActionPerformed
        // TODO add your handling code here:
        jlbDoctor.setText("Dr.Josefa Martínez");
    }//GEN-LAST:event_rdbEspecialista3ActionPerformed

    private void rdbEspecialista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEspecialista1ActionPerformed
        // TODO add your handling code here:
        jlbDoctor.setText("Licenciada Adriana Añamisi");
    }//GEN-LAST:event_rdbEspecialista1ActionPerformed

    private void rdbEspecialista2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEspecialista2ActionPerformed
        // TODO add your handling code here:
        jlbDoctor.setText("Licenciada Joselyn Segovia");
    }//GEN-LAST:event_rdbEspecialista2ActionPerformed

    private void rdbEspecialista4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEspecialista4ActionPerformed
        // TODO add your handling code here:
        jlbDoctor.setText("Licenciada Sofía suntaxi");
    }//GEN-LAST:event_rdbEspecialista4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.ButtonGroup btnGrupo2;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jblFecha;
    private javax.swing.JLabel jlbDisponible;
    private javax.swing.JLabel jlbDoctor;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JRadioButton rdbEspecialista1;
    private javax.swing.JRadioButton rdbEspecialista2;
    private javax.swing.JRadioButton rdbEspecialista3;
    private javax.swing.JRadioButton rdbEspecialista4;
    // End of variables declaration//GEN-END:variables

    public String getNombre() {
        return nombre;
    }

    public String getOcupacion() {
        return ocupacion;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }

}
