/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import centrorehabilitacionfisica.Medico;
import centrorehabilitacionfisica.Turno;
import java.util.Date;

/**
 *
 * @author Willy
 */
public class Citas extends javax.swing.JFrame {

    /**
     * Creates new form Citas
     */
    public Citas() {
        initComponents();
        rdbEspecialista1.setVisible(false);
           rdbEspecialista2.setVisible(false);
           rdbEspecialista3.setVisible(false);
           rdbEspecialista4.setVisible(false);
    }
    
     Turno turno = new Turno();
   
     private String nombre;
    private String ocupacion;
    
     public String getNombre() {
        return nombre;
    }

    public String getOcupacion() {
        return ocupacion;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    
    
     public void datos(){
        if(rdbEspecialista1.isSelected()==true)
            setNombre("FISIOTERAPIA");
            setOcupacion("Licenciada Adriana Añamisi");
        if(rdbEspecialista2.isSelected()==true)
           setNombre("NUTRICION");
        setOcupacion("Licenciada Joselyn Segovia");
        if(rdbEspecialista3.isSelected()==true)
            setNombre("MEDICINA GENERAL");
        setOcupacion("Dr.Josefa Martínez");
        if(rdbEspecialista4.isSelected()==true)
            setNombre("TERAPIA OCUPACIONAL");
            setOcupacion("Licenciada Sofía suntaxi");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jlbDisponible = new javax.swing.JLabel();
        jblFecha = new javax.swing.JButton();
        rdbEspecialista1 = new javax.swing.JRadioButton();
        rdbEspecialista2 = new javax.swing.JRadioButton();
        rdbEspecialista3 = new javax.swing.JRadioButton();
        rdbEspecialista4 = new javax.swing.JRadioButton();
        btnAgendar = new javax.swing.JButton();
        calendar = new com.toedter.calendar.JCalendar();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel2.setText("AGENDAR CITA");

        jlbDisponible.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jlbDisponible.setText("ESPECIALIdades");

        jblFecha.setFont(new java.awt.Font("Stencil", 1, 12)); // NOI18N
        jblFecha.setText("Confirmar Fecha");
        jblFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblFechaActionPerformed(evt);
            }
        });

        rdbEspecialista1.setText("FISIOTERAPIA");

        rdbEspecialista2.setText("NUTRICION");

        rdbEspecialista3.setText("MEDICINA GENERAL");
        rdbEspecialista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEspecialista3ActionPerformed(evt);
            }
        });

        rdbEspecialista4.setText("TERAPIA OCUPACIONAL");

        btnAgendar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnAgendar.setText("AGENDAR");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(108, 108, 108)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(103, 103, 103))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jblFecha)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jlbDisponible)
                                    .addGap(3, 3, 3))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(123, 123, 123)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(rdbEspecialista1)
                                        .addComponent(rdbEspecialista2)
                                        .addComponent(rdbEspecialista3)
                                        .addComponent(rdbEspecialista4)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(btnAgendar)))))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(36, 36, 36)
                    .addComponent(jlbDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(18, 18, 18)
                    .addComponent(rdbEspecialista1)
                    .addGap(18, 18, 18)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(rdbEspecialista2)
                            .addGap(28, 28, 28)
                            .addComponent(rdbEspecialista3)))
                    .addGap(18, 18, 18)
                    .addComponent(rdbEspecialista4)
                    .addGap(59, 59, 59)
                    .addComponent(btnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
        Ingreso ingreso = new Ingreso();
        ingreso.setVisible(true);
        Citas.this.dispose();
    }//GEN-LAST:event_mnSalirActionPerformed
    private void jblFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblFechaActionPerformed
        if(turno.tomarCita(1)==true){
            rdbEspecialista1.setVisible(true);
            rdbEspecialista2.setVisible(true);
            rdbEspecialista3.setVisible(false);
            rdbEspecialista4.setVisible(false);

        }else{
            rdbEspecialista1.setVisible(false);
            rdbEspecialista2.setVisible(false);
            rdbEspecialista3.setVisible(true);
            rdbEspecialista4.setVisible(true);
        }
    }//GEN-LAST:event_jblFechaActionPerformed

    private void rdbEspecialista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEspecialista3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbEspecialista3ActionPerformed

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
        Especialista especialista = new Especialista();
        especialista.setVisible(true);
        Citas.this.dispose();
    }//GEN-LAST:event_btnAgendarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Citas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Citas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private com.toedter.calendar.JCalendar calendar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jblFecha;
    private javax.swing.JLabel jlbDisponible;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JRadioButton rdbEspecialista1;
    private javax.swing.JRadioButton rdbEspecialista2;
    private javax.swing.JRadioButton rdbEspecialista3;
    private javax.swing.JRadioButton rdbEspecialista4;
    // End of variables declaration//GEN-END:variables
}
