/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import centrorehabilitacionfisica.Medico;
import centrorehabilitacionfisica.Turno;
import javax.swing.JOptionPane;
/**
 *
 * @author USUARIO
 */
public class Cita extends javax.swing.JFrame {

    /**
     * Creates new form Cita
     */
    Turno turno = new Turno();
    Medico medico = new Medico();
    //Especialista especialista = new Especialista();
     private String nombre;
    private String ocupacion;
    
     public String getNombre() {
        return nombre;
    }

    public String getOcupacion() {
        return ocupacion;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public void setOcupacion(String ocupacion) {
        this.ocupacion = ocupacion;
    }
    public Cita() {
        
        initComponents();
           rdbEspecialista1.setVisible(false);
           rdbEspecialista2.setVisible(false);
           rdbEspecialista3.setVisible(false);
           rdbEspecialista4.setVisible(false);

    }
    
    
    
    public void datos(){
        if(rdbEspecialista1.isSelected()==true)
            setNombre("FISIOTERAPIA");
            setOcupacion("Licenciada Adriana Añamisi");
        if(rdbEspecialista2.isSelected()==true)
           setNombre("NUTRICION");
        setOcupacion("Licenciada Joselyn Segovia");
        if(rdbEspecialista3.isSelected()==true)
            setNombre("MEDICINA GENERAL");
        setOcupacion("Dr.Josefa Martínez");
        if(rdbEspecialista4.isSelected()==true)
            setNombre("TERAPIA OCUPACIONAL");
            setOcupacion("Licenciada Sofía suntaxi");
    }
    
          
      
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrupo = new javax.swing.ButtonGroup();
        btnGrupo2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnAgendar = new javax.swing.JButton();
        rdbEspecialista1 = new javax.swing.JRadioButton();
        rdbEspecialista2 = new javax.swing.JRadioButton();
        rdbEspecialista3 = new javax.swing.JRadioButton();
        rdbEspecialista4 = new javax.swing.JRadioButton();
        jlbDisponible = new javax.swing.JLabel();
        calendar = new com.toedter.calendar.JDateChooser();
        jblFecha = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 36)); // NOI18N
        jLabel2.setText("AGENDAR CITA");

        btnAgendar.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 18)); // NOI18N
        btnAgendar.setText("AGENDAR");
        btnAgendar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarActionPerformed(evt);
            }
        });

        btnGrupo.add(rdbEspecialista1);
        rdbEspecialista1.setText("FISIOTERAPIA");
        rdbEspecialista1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEspecialista1ActionPerformed(evt);
            }
        });

        btnGrupo.add(rdbEspecialista2);
        rdbEspecialista2.setText("NUTRICION");

        btnGrupo.add(rdbEspecialista3);
        rdbEspecialista3.setText("MEDICINA GENERAL");
        rdbEspecialista3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbEspecialista3ActionPerformed(evt);
            }
        });

        btnGrupo.add(rdbEspecialista4);
        rdbEspecialista4.setText("TERAPIA OCUPACIONAL");

        jlbDisponible.setFont(new java.awt.Font("Stencil", 1, 18)); // NOI18N
        jlbDisponible.setText("ESPECIALIdades");

        calendar.setFont(new java.awt.Font("Perpetua Titling MT", 1, 12)); // NOI18N
        calendar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                calendarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                calendarKeyTyped(evt);
            }
        });

        jblFecha.setFont(new java.awt.Font("Stencil", 1, 12)); // NOI18N
        jblFecha.setText("Confirmar Fecha");
        jblFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jblFechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(193, 193, 193))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jblFecha)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlbDisponible)
                        .addGap(93, 93, 93))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(123, 123, 123)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rdbEspecialista1)
                                    .addComponent(rdbEspecialista2)
                                    .addComponent(rdbEspecialista3)
                                    .addComponent(rdbEspecialista4)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(btnAgendar)))
                        .addContainerGap(90, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(calendar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(rdbEspecialista1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jblFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rdbEspecialista2)
                                .addGap(28, 28, 28)
                                .addComponent(rdbEspecialista3)))))
                .addGap(18, 18, 18)
                .addComponent(rdbEspecialista4)
                .addGap(59, 59, 59)
                .addComponent(btnAgendar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jMenu1.setText("Menu");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        mnSalir.setText("Salir");
        mnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(mnSalir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarActionPerformed
            Especialista especialista = new Especialista(Cita.this);
            especialista.setVisible(true);
            //Cita.this.dispose();
    }//GEN-LAST:event_btnAgendarActionPerformed

    private void mnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSalirActionPerformed
            Ingreso ingreso = new Ingreso();
            ingreso.setVisible(true);
            Cita.this.dispose();
    }//GEN-LAST:event_mnSalirActionPerformed

    private void calendarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarKeyPressed

    }//GEN-LAST:event_calendarKeyPressed

    private void calendarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_calendarKeyTyped
       
    }//GEN-LAST:event_calendarKeyTyped

    private void jblFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jblFechaActionPerformed
        if(turno.tomarCita(calendar.getDate().getDate())==true){
           rdbEspecialista1.setVisible(true);
           rdbEspecialista2.setVisible(true);
           rdbEspecialista3.setVisible(false);
           rdbEspecialista4.setVisible(false);
          
       }else{
           rdbEspecialista1.setVisible(false);
           rdbEspecialista2.setVisible(false);
           rdbEspecialista3.setVisible(true);
           rdbEspecialista4.setVisible(true);
       }
    }//GEN-LAST:event_jblFechaActionPerformed

    private void rdbEspecialista3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEspecialista3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbEspecialista3ActionPerformed

    private void rdbEspecialista1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbEspecialista1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdbEspecialista1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cita.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cita().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendar;
    private javax.swing.ButtonGroup btnGrupo;
    private javax.swing.ButtonGroup btnGrupo2;
    private com.toedter.calendar.JDateChooser calendar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jblFecha;
    private javax.swing.JLabel jlbDisponible;
    private javax.swing.JMenuItem mnSalir;
    private javax.swing.JRadioButton rdbEspecialista1;
    private javax.swing.JRadioButton rdbEspecialista2;
    private javax.swing.JRadioButton rdbEspecialista3;
    private javax.swing.JRadioButton rdbEspecialista4;
    // End of variables declaration//GEN-END:variables
}
